weight = 2
languageCode = "en"
languageName = "English"

[params.author]
name = "Mulberror"

# 中文标题
[params.header.title]
# 标题名
name = """
Unnoted Melody
"""
pre = "<i class='far fa-edit fa-fw'></i>"

[params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
# FixIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
# 头像的链接指向的 URL
avatarLinkURL = "https://blog.mulbx.top/en/"
title = "Mulberror's Blog"
# 主页显示的网站副标题
subtitle = """Hope one day, you'll be reunited with the one you cherish."""
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
# FixIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
disclaimer = ""

[params.sponsor]
enable = true
bio = "If you find my creation helpful, I would be pleased if get a free coffee~"
link = "" # The link to your sponsor page
custom = "" # Custom HTML button

[params.home.posts]
enable = true
# special amount of posts in each home posts page
paginate = 10
