weight = 1
# language code, CN only here
languageCode = "zh-CN"
languageName = "简体中文"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = true

[params.author]
name = "森绪"

# 中文标题
[params.header.title]
# 标题名
name = """
未定的旋律
"""
pre = "<i class='far fa-edit fa-fw'></i>"

# FixIt 新增 | 0.2.13 赞赏配置
[params.sponsor]
enable = true
bio = "如果觉得我的文章有帮助，欢迎赠我一杯免费的咖啡~"
link = "" # 你的赞赏页面的地址
custom = "" # 自定义 HTML

[params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
# gravatarEmail = "mulberror@gmail.com"
# 头像的链接指向的 URL
avatarLinkURL = "https://blog.mulbx.top/"
# FixIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
title = "莫泊瑞的博客"
# 主页显示的网站副标题
subtitle = "与其抱怨长夜，何不秉烛夜行。"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
# FixIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
disclaimer = ""

[params.home.posts]
enable = true
# special amount of posts in each home posts page
paginate = 10

# FixIt 更改 | 0.2.7 第三方库文件的 CDN 设置
# [params.cdn]
#   # CDN 数据文件名称, 默认不启用
#   # 位于 "themes/FixIt/assets/data/cdn/" 目录
#   # 可以在你的项目下相同路径存放你自己的数据文件:
#   # "assets/data/cdn/"
#   data = "jsdelivr.yml"
