# -------------------------------------------------------------------------------------
# Menu Configuration | 菜单配置
# See: https://fixit.lruihao.cn/zh-cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
identifier = "homepage"
pre = """<i class="fa-solid fa-house"></i>"""
post = ""
name = "Home"
url = "/"
title = ""
weight = 10

[[main]]
identifier = "archives"
pre = """<i class="fa-solid fa-feather"></i>"""
name = "Archives"
url = "/archives/"
title = ""
weight = 20

[[main]]
identifier = "collections"
parent = "archives"
pre = """<i class="fa-solid fa-layer-group"></i>"""
post = ""
name = "Collections"
url = "/collections/"
title = ""
weight = 30

[[main]]
identifier = "categories"
parent = "archives"
pre = """<i class="fa-solid fa-folder-tree"></i>"""
post = ""
name = "Category"
url = "/categories/"
title = ""
weight = 50

[[main]]
identifier = "Tags"
parent = "archives"
pre = """<i class="fa-solid fa-tags"></i>"""
post = ""
name = "Tags"
url = "/tags/"
title = ""
weight = 70

[[main]]
identifier = "links"
pre = """<i class="fa-solid fa-link"></i>"""
post = ""
name = "Links"
url = ""
title = ""
weight = 75

[[main]]
identifier = "friends"
pre = """<i class="fa-solid fa-paper-plane"></i>"""
parent = "links"
post = ""
name = "Friends"
url = "/friends"
title = ""
weight = 80

[[main]]
identifier = "note"
pre = """<i class="fa-solid fa-pen-to-square"></i>"""
parent = "links"
post = ""
name = "Notebook"
url = "https://note.mulbx.top"
title = ""
weight = 81

[[main]]
identifier = "time"
pre = """<i class="fa-solid fa-film"></i>"""
# parent = ""
post = ""
name = "Time"
url = "/time"
title = ""
weight = 85

[[main]]
identifier = "prospect"
pre = """<i class="fa-solid fa-rocket"></i>"""
parent = "time"
post = ""
name = "Prospect"
url = "/time/prospect"
title = ""
weight = 86

[[main]]
identifier = ""
pre = """<i class="fa-solid fa-backward"></i>"""
parent = "time"
post = ""
name = "Review"
url = "/time/review"
title = ""
weight = 87

[[main]]
identifier = "about"
pre = """<i class="fa-solid fa-circle-info"></i>"""
post = ""
name = "About"
url = "/about/"
title = ""
weight = 90
