version = "0.3.0"

description = "Mulberror's Unnoted Melody"

# 网站关键词
keywords = [
  "Mulberror",
  "Blog",
  "森绪",
  "莫柏瑞",
  "Full-Stack",
  "Computer Science",
  "Mathematics",
]

# 网站默认主题样式 ("light", "dark", "auto")
defaultTheme = "auto"
# FixIt 新增 | 0.2.11 开启 PWA 支持
enablePWA = false

[author]
name = "Mulberror"
email = "mulberror@gmail.com"
link = "https://blog.mulbx.top"
avatar = ""
# gravatarEmail = "mulberror@gmail.com"

# FixIt 新增 | 0.2.0 List (目录或标签) 页面配置
[list]
# list 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

# 主页配置
[home]
# FixIt 新增 | 0.2.0 RSS 文章数目
rss = 10

# 主页个人信息
[home.profile]
enable = true
# Gravatar 邮箱, 用于优先在主页显示的头像
# gravatarEmail = "mulberror@gmail.com"
# 主页显示头像的 URL
avatarURL = "/img/author/avatar.webp"
# 将你的头像文件放置于 static 或者 assets 目录下
# 文件路径是相对于 static 或者 assets 目录的

[social]
GitHub = "mulberror"
Email = "mulberror@gmail.com"
Bilibili = "228169364"
RSS = true

[gitInfo]
repo = "https://github.com/mulberror/mulberror"
branch = "main"
dir = "content"

[cookieconsent]
enable = false
[cookieconsent.content]
message = ""
dismiss = ""
link = ""

# map 返回顶部按钮配置。
[backToTop]
enable = true
scrollpercent = true

# map 页面加载期间顶部的进度条，详见 Pace.js。
[pace]
enable = true
color = "orange"
theme = "minimal"

# map 标签云配置。
[tagcloud]
enable = true
min = 14
max = 32
peakCount = 10
orderby = "name"

[page]
# FixIt 0.2.18 | 新增 是否启用文章作者头像
authorAvatar = true
# 是否在主页隐藏一篇文章
hiddenFromHomePage = false
# 是否在搜索结果中隐藏一篇文章
hiddenFromSearch = false
# FixIt 0.3.0 | 新增 是否在相关文章中隐藏一篇文章
hiddenFromRelated = false
# FixIt 0.3.10 | 新增 是否在 RSS、Atom 和 JSON feed 中隐藏一篇文章
hiddenFromFeed = false
# 是否使用 twemoji
twemoji = false
# FixIt 0.2.18 | 更改 是否使用 lightgallery
# 设为 true，图片设置标题时，文章中的图片将以画廊形式呈现，例如：![alt](src "title")
# 设为 "force"，无论图片是否设置标题文章中的图片都将强制按照画廊形式呈现，例如：![alt](src)
lightgallery = false
# 是否使用 ruby 扩展语法
ruby = true
# 是否使用 fraction 扩展语法
fraction = true
# 是否使用 fontawesome 扩展语法
fontawesome = true
# 许可协议信息（支持 HTML 格式）
license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
# 是否显示原始 Markdown 文档内容的链接
linkToMarkdown = true
# FixIt 0.3.0 | 新增 是否显示查看文章源码的链接
linkToSource = false
# FixIt 0.3.0 | 新增 是否显示编辑文章的链接
linkToEdit = false
# FixIt 0.3.0 | 新增 是否显示报告文章问题的链接
linkToReport = false
# FixIt 0.3.10 | 更改 页面样式 ["narrow", "normal", "wide", ...]
pageStyle = "narrow"
# FixIt 0.2.17 | 更改 开启自动书签支持
# 如果为 true，则在关闭页面时保存阅读进度
autoBookmark = false
# FixIt 0.2.17 | 新增 是否使用 字数统计
wordCount = true
# FixIt 0.2.17 | 新增 是否使用 预计阅读
readingTime = true
# FixIt 0.2.17 | 新增 文章结束标志
endFlag = ""
# FixIt 0.2.18 | 新增 是否开启即时页面
instantPage = false
# FixIt 0.3.0 | 新增 是否在侧边栏显示集合列表
collectionList = false
# FixIt 0.3.0 | 新增 是否在文章末尾显示集合导航
collectionNavigation = true

# FixIt 新增 | 0.2.13 过时文章提示
[page.outdatedArticleReminder]
enable = true
# 如果文章最后更新于 90 天之前，显示提醒
reminder = 90
# 如果文章最后更新于 180 天之前，显示警告
warning = 180

# FixIt 新增 | 0.2.0 目录配置
[page.toc]
# 是否使用目录
enable = true
# 是否保持使用文章前面的静态目录
keepStatic = false
# 是否使侧边目录自动折叠展开
auto = true
# FixIt 0.2.13 | 新增 目录位置 ["left", "right"]
position = "right"
# FixIt 0.3.12 | 新增 取代 `markup.tableOfContents` 设置
ordered = true
startLevel = 2
endLevel = 6

# FixIt 0.3.0 | 新增 页面标题配置
[page.heading]
# FixIt 0.3.6 | 新增 是否自动大写标题
capitalize = false
# FixIt 0.3.12 | 更改 必须设置 `params.page.toc.ordered` 为 true
[page.heading.number]
# 是否启用自动标题编号
enable = true
[page.heading.number.format]
h1 = "{title}"
h2 = "{h2} {title}"
h3 = "{h2}.{h3} {title}"
h4 = "{h2}.{h3}.{h4} {title}"
h5 = "{h2}.{h3}.{h4}.{h5} {title}"
h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"

# FixIt 更改 | 0.2.0 KaTeX 数学公式
[page.math]
enable = true
# 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# 默认行内定界符是 $ ... $ 和 \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX 插件 copy_tex
copyTex = true
# KaTeX 插件 mhchem
mhchem = true

# FixIt 新增 | 0.2.0 Mapbox GL JS 配置
[page.mapbox]
# Mapbox GL JS 的 access token
accessToken = ""
# 浅色主题的地图样式
lightStyle = "mapbox://styles/mapbox/light-v9"
# 深色主题的地图样式
darkStyle = "mapbox://styles/mapbox/dark-v9"
# 是否添加 NavigationControl
navigation = true
# 是否添加 GeolocateControl
geolocate = true
# 是否添加 ScaleControl
scale = true
# 是否添加 FullscreenControl
fullscreen = true

# FixIt 更改 | 0.2.0 文章页面的分享信息设置
[page.share]
enable = true
Twitter = true
Facebook = true
Linkedin = false
Whatsapp = false
Pinterest = false
Tumblr = false
HackerNews = false
Reddit = false
VK = false
Buffer = false
Xing = false
Line = true
Instapaper = false
Pocket = false
Digg = false
Stumbleupon = false
Flipboard = false
Weibo = true
Renren = false
Myspace = false
Blogger = true
Baidu = true
Odnoklassniki = false
Evernote = false
Skype = false
Trello = false
Mix = false
Mastodon = false

# Comment config
# 评论系统设置
[page.comment]
enable = true
# Disqus comment config (https://disqus.com/)
# Disqus 评论系统设置 (https://disqus.com/)
[page.comment.disqus]
enable = false
# Disqus shortname to use Disqus in posts
# Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
shortname = ""
# Gitalk comment config (https://github.com/gitalk/gitalk)
# Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
[page.comment.gitalk]
enable = false
owner = ""
repo = ""
clientId = ""
clientSecret = ""
# Valine comment config (https://github.com/xCss/Valine)
# Valine 评论系统设置 (https://github.com/xCss/Valine)
[page.comment.valine]
enable = false
appId = ""
appKey = ""
placeholder = ""
avatar = "mp"
meta = ""
pageSize = 10
lang = "en"
visitor = true
recordIP = false
highlight = true
enableQQ = false
serverURLs = ""
# emoji data file name, default is "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# located in "themes/FixIt/assets/data/emoji/" directory
# you can store your own data files in the same path under your project:
# "assets/data/emoji/"
# emoji 数据文件名称, 默认是 "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# 位于 "themes/FixIt/assets/data/emoji/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件:
# "assets/data/emoji/"
emoji = ""
# Waline comment config (https://waline.js.org)
# Waline 评论系统设置 (https://waline.js.org)
[page.comment.waline]
enable = false
serverURL = "https://waline-comment-FixIt.vercel.app/"
pageview = true
comment = true
# emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
# meta = ['nick', 'mail', 'link']
# requiredMeta = []
# login = 'enable'
# wordLimit = 0
# pageSize = 10
# imageUploader = false
# highlighter = false
# texRenderer = false
# Facebook comment config (https://developers.facebook.com/docs/plugins/comments)
# Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
[page.comment.facebook]
enable = false
width = "100%"
numPosts = 10
appId = ""
languageCode = ""
# Telegram comments config (https://comments.app/)
# Telegram comments 评论系统设置 (https://comments.app/)
[page.comment.telegram]
enable = false
siteID = ""
limit = 5
height = ""
color = ""
colorful = true
dislikes = false
outlined = false
dark = false
# Commento comment config (https://commento.io/)
# Commento comment 评论系统设置 (https://commento.io/)
[page.comment.commento]
enable = false
# Utterances comment config (https://utteranc.es/)
# Utterances comment 评论系统设置 (https://utteranc.es/)
[page.comment.utterances]
enable = true
# owner/repo
repo = "mulberror/blog-comments"
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
darkTheme = "github-dark"
# Twikoo comment config (https://twikoo.js.org/)
# Twikoo comment 评论系统设置 (https://twikoo.js.org/)
[page.comment.twikoo]
enable = false
envId = "https://twikoo-comments-FixIt.vercel.app/"
region = ""
path = ""
cloudbase = true                                    # boolean : true / false. # 是否部署在腾讯云 CloudBase
visitor = true
commentCount = true
# Vssue comment config (https://vssue.js.org//)
# Vssue comment 评论系统设置 (https://vssue.js.org//)
[page.comment.vssue]
enable = false
platform = ""     # ("bitbucket", "gitea", "gitee", "github", "gitlab")
owner = ""
repo = ""
clientId = ""
clientSecret = ""
# Remark42 comment config (https://remark42.com/)
# Remark42 comment 评论系统设置 (https://remark42.com/)
[page.comment.remark42]
enable = false
host = ""
site_id = ""
max_shown_comments = 15
show_email_subscription = true
simple_view = false
# giscus comment config (https://giscus.app/)
# giscus comment 评论系统设置 (https://giscus.app/)
[page.comment.giscus]
enable = false
# owner/repo
dataRepo = "mulberror/blog-comments"
dataRepoId = "R_kgDONF-bHA"
dataCategory = "Announcements"
dataCategoryId = "DIC_kwDONF-bHM4Cjxi8"
dataMapping = "pathname"
dataStrict = "0"
dataReactionsEnabled = "1"
dataEmitMetadata = "0"
dataInputPosition = "bottom"
lightTheme = "light"
darkTheme = "dark"
dataLang = "en"
dataLoading = "lazy"
# artalk comment config (https://artalk.js.org/guide/frontend/config.html)
# artalk comment 评论系统设置 (https://artalk.js.org/guide/frontend/config.html)
[page.comment.artalk]
enable = false
server = ""
site = ""
lite = false
katex = false
lightbox = false
pageview = true
commentCount = true
# Third-party library config
# 第三方库配置
[page.library]
[page.library.css]
# someCSS = "some.css"
# [page.library.css.someOtherCSS]
#   src = "someOther.css"
#   defer = true
#   attr = "customAttribute"
# located in "assets/" 位于 "assets/"
# Or 或者
# someCSS = "https://cdn.example.com/some.css"
[page.library.js]
# someJavaScript = "some.js"
# [page.library.js.someOtherJavaScript]
#   src = "someOther.js"
#   defer = false
#   async = true
#   attr = "customAttribute"
# located in "assets/" 位于 "assets/"
# Or 或者
# someJavascript = "https://cdn.example.com/some.js"
# Page SEO config
# 页面 SEO 配置
[page.seo]
# image URL
# 图片 URL
images = []
# Publisher info
# 出版者信息
[page.seo.publisher]
name = "mulberror"
logoUrl = "/img/author/avatar.webp"
# Related content config
# 相关文章推荐配置
[page.related]
enable = true
count = 3

# 页面头部导航栏配置
[header]
# string 桌面端导航栏模式，可选值：sticky、normal、auto, 默认：sticky。
desktopMode = "sticky"
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"
# FixIt 新增 | 0.2.0 页面头部导航栏标题配置
[header.title]
# LOGO 的 URL（不要设置这个！）
logo = ""
# 标题名称
# name = """
# <svg class="icon" viewBox="0 0 576 512"><path d="M402.3 344.9l32-32c5-5 13.7-1.5 13.7 5.7V464c0 26.5-21.5 48-48 48H48c-26.5.0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h273.5c7.1.0 10.7 8.6 5.7 13.7l-32 32c-1.5 1.5-3.5 2.3-5.7 2.3H48v352h352V350.5c0-2.1.8-4.1 2.3-5.6zm156.6-201.8L296.3 405.7l-90.4 10c-26.2 2.9-48.5-19.2-45.6-45.6l10-90.4L432.9 17.1c22.9-22.9 59.9-22.9 82.7.0l43.2 43.2c22.9 22.9 22.9 60 .1 82.8zM460.1 174 402 115.9 216.2 301.8l-7.3 65.3 65.3-7.3L460.1 174zm64.8-79.7-43.2-43.2c-4.1-4.1-10.8-4.1-14.8.0L436 82l58.1 58.1 30.9-30.9c4-4.2 4-10.8-.1-14.9z"></path></svg>
# Blank Notebook
# """
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = "<i class='far fa-edit fa-fw'></i>"
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
# FixIt 新增 | 0.2.5 是否为标题显示打字机动画
typeit = true

# map 面包屑导航配置。
[breadcrumb]
enable = true
sticky = true
showHome = true
separator = "/"
capitalize = false

[navigation]
inSection = true
reverse = false

# Footer config
# 页面底部信息配置
[footer]
enable = true
# Custom content (HTML format is supported)
# 自定义内容 (支持 HTML 格式)
# whether to show Hugo and theme info
# 是否显示 Hugo 和主题信息
hugo = true
# FixIt 新增 | 0.2.14 托管服务信息 (支持 HTML 格式)
hostedOn = '<a title="Vercel" href="https://vercel.com/" target="_blank" rel="noopener noreffer">Vercel</a>'
# whether to show copyright info
# 是否显示版权信息
copyright = true
# whether to show the author
# 是否显示作者
author = true
# site creation time
# 网站创立年份
since = 2024
# ICP info only in China (HTML format is supported)
# ICP 备案信息，仅在中国使用 (支持 HTML 格式)
icp = ""
# license info (HTML format is supported)
# 许可协议信息 (支持 HTML 格式)
license = """
      <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>
    """

[analytics.google]
id = "G-BSBYR0BB64"
# 是否匿名化用户 IP
anonymizeIP = true

[verification]
google = "MQ8DNu27ayX6B_4ObiEDK09vGr1fdy7kOAnbd09hJk4"
bing = ""
yandex = ""
pinterest = ""
baidu = "codeva-th8nzaQhTh"
so = ""
sogou = ""
